jsf:
  projectStage: Development
  primefaces:
    theme: bootstrap
  bootsfaces:
    usetheme: true	

security:
  basic:
    enabled: false
    
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/tehara
    username: tehara
    password: tehara
    driverClassName: com.mysql.jdbc.Driver